# Generated by Django 4.2.2 on 2023-06-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emai', models.CharField(max_length=30)),
                ('Nombre_usuario', models.CharField(max_length=20)),
                ('contrasenia', models.CharField(max_length=20)),
                ('Direccion_entregas', models.CharField(max_length=30)),
            ],
        ),
    ]
