# Generated by Django 4.2.2 on 2023-07-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_alter_infoextra_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='fecha_nacimiento',
            field=models.TimeField(null=True),
        ),
    ]
