# Generated by Django 4.2.2 on 2023-07-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_alter_infoextra_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoextra',
            name='fecha_nacimiento',
        ),
    ]
