# Generated by Django 4.2.2 on 2023-07-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0002_alter_chat_options_remove_mensaje_leido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
